# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'TodoList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoList
  pod 'SnapKit', '~> 5.6.0'

  target 'TodoListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoListUITests' do
    # Pods for testing
  end

end
